networks:
  mg_projects:
    driver: bridge
services:
  nginx:
    container_name: mg_projects_nginx
    environment:
      MG_PROXY: ${MG_PROXY:-https://master.molgenis.org}
      MG_THEME: ${MG_THEME:-molgenis-blue}
    image: nginx
    networks:
      - mg_projects
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.tpl:/tmp/localhost.tpl
      - ../:/usr/share/nginx/html
    command: >
      /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
      < /tmp/localhost.tpl
      > /etc/nginx/localhost
      && nginx -g 'daemon off;'"

version: "3.8"
