name: CI
on: push
jobs:
  test:
    runs-on: Ubuntu 20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install
      - name: Lint SCSS files
        run: yarn lint
      - name: Build Molgenis themes
        run: yarn build --all
      - name: Publish to Npm/Unpkg
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
